language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml -s src
